# Form implementation generated from reading ui file 'Main1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 642)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 20, 721, 501))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.save_b = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_b.setGeometry(QtCore.QRect(30, 540, 191, 61))
        self.save_b.setObjectName("save_b")
        self.edit_b = QtWidgets.QPushButton(parent=self.centralwidget)
        self.edit_b.setGeometry(QtCore.QRect(340, 540, 211, 61))
        self.edit_b.setObjectName("edit_b")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.save_b.setText(_translate("MainWindow", "Создать"))
        self.edit_b.setText(_translate("MainWindow", "Редактировать"))
